= Android Project Standards
include::include.adoc[]

This is a living document. To request changes, please open a pull request.

The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL
NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED",  "MAY", and
"OPTIONAL" in this document are to be interpreted as described in
https://www.ietf.org/rfc/rfc2119.txt[RFC 2119].

= Git

== Location and Naming

One20 MUST use git, specifically Github for all projects. 
Project names MUST be written in the form of `android-{project_name}` (all lower case) 
or if a library project `android-library-{libraryName}`.

== Branching

Android projects will use git-flow style of branching and merging. Checkout
https://www.atlassian.com/git/tutorials/comparing-workflows#gitflow-workflow[Atlassian's Documentation]
and this http://nvie.com/posts/a-successful-git-branching-model/[helpful guide]
for more information. We are not using develop branches and we encourage individual developers to fork 
the project repo they are working out of.

In addition to having a review, the branch MUST pass a merge build from
<<Continuous Integration>>. This is a build that confirms that the code once
merged into master will not break the build.

== Forking

Although not required, it is RECOMMENDED to fork repositories under your user
account. This prevents clutter and reduces the work of figuring out which
branches can and should be deleted. Under your own fork, you are in charge of
all the branches and can delete and save them as you see fit.

IMPORTANT: If using a fork you MUST set the 'Repository Permissions' to allow
the *Production Group* to read. This allows any developer to access and see what
you are working on. Just in case you forget to create a PR before you go on
vacation.

== Releases

NOTE: A release is defined as the code that is currently or soon to be in the
Play Store.

All release builds MUST be tagged. The proper format for a tag would be
`v{major}.{minor}.{patch}`.

TIP: Don't forget to push the tags to the remote (Github).

An example would be:
```
git tag -a v1.0.0 # -a is not required but RECOMMENDED
git push origin v1.0.0
```

== Release Branching Strategy

The goal of this document is to outline a typical path for releases in git.

We'll start with the following working tree:

    A---B (master)

Now we'll start working on a feature. At this point, we'll open up a topic
branch to work on.

    git checkout -b topic

After doing some work in our topic branch, we make a commit and our working tree
will look like the following:

          C (topic)
         /
    A---B (master)

Now our Topic is ready to be reviewed. We'll open up a Pull Request targeting
the `master` branch for peer review. At this point someone points out a typo in
a comment. We'll fix the issue and make a commit. Our local working Tree now
looks like the following:

          C---D (topic)
         /
    A---B (master)

Before we push, we'll clean up these commits. Since the changes made in D were a
mistake, they should have been in C to begin with. For a situation like this it
makes sense to combine these commits together. We'll do that with an interactive
rebase.

    git rebase -i HEAD~2

This will bring up an editor that looks something like the following:

    pick C some message for changes in C
    pick D Fixing typo in C

    # Rebase 1f057e2..d965c4b onto 1f057e2

This editor allows us to re-arrange, modify and squash commits. In this case we
want to squash C up the tree into D. We do this by changing the word `pick` in
front of the D commit to `squash` like the following:

    pick C some message for changes in C
    squash D Fixing typo in C

    # Rebase 1f057e2..d965c4b onto 1f057e2

After this, it will allow you to change the commit message, and afterwards we'll
have a new commit in place of C and D. Our tree will look something like this:

          E (topic)
         /
    A---B (master)

Next we'll push our changes for approval. We've re-written the tree, evident by
the fact that commit C no longer exists. So we'll need to do a force push here.
We'll only want to force push our topic branch so we'll be specific in our push
command:

    git push --force origin topic

Once our new Changes have been approved, we can merge these changes from github
on the pull request. This is the equivalent of running the command from the
master branch:

    git merge --no-ff topic

In either case, we'll end up with the following tree:

          E
         / \
    A---B---F (master)

Now we think our branch is ready for release. Since there are bound to be some
QA fixes before it's actually released, we'll open up a separate branch for the
minor release. This will allow us to work on new functionality in the `master`
branch while we work on QA fixes in the release branch.
When we do this, our tree will initially look like this, with master and the
release branch pointing at the same commit:

          E
         / \
    A---B---F (master / 1.6.x)

Now we'll start working on a new feature. Something that will not be in our
upcoming release, but we want to start working on. Just like before we'll open
up a new topic branch and start committing to it:

          E   G---H (new-topic)
         / \ /
    A---B---F (master / 1.6.x)

Meanwhile, we'll also make a bugfix to the release branch fixing some QA issues.
We'll branch off of the release branch `1.6.x` and start making changes.
Our Tree may look like this:

          E   G---H (new-topic)
         / \ /
    A---B---F (master)
             \
              I (1.6.x)

Next we need to synchronize our release and master branch. This must happen for
two man reasons.
Firstly, This bug may also exist in our `master` branch, so we'll need to merge
it upwards.
Secondly, we want to ensure that all of these commits can be reached from our
master working tree. This will become important when our release gets tagged
later.
Assuming there are no conflicts, this may be done without a pull request, since
the changes will have already been approved for the release branch. We can
merge our changes in the release branch by running:

    git merge --no-ff 1.6.x

Afterwards we'll have a commit tree like the following:

         E   G---H (new-topic)
        / \ /
    A---B--F---J (master)
            \ /
             I (1.6.x)


QA Has now approved our changes, and our release is being published. We'll mark
the commit that was released with a tag.
We'll do that by making a [signed tag][2] with the format `vX.Y.Z` and pushing
it.

    git tag -s v1.6.9

Now our tree will look something like:

          E   G---H (new-topic)
         / \ /
    A---B---F---J (master)
             \ /
              I (1.6.x)
               \
                * (Tag: v1.6.9)

At this point we can also close our release branch `1.6.x`. If there are more
bugfixes that are needed on that release, we can always re-open the branch using
the tag.

          E   G---H (new-topic)
         / \ /
    A---B---F---J (master)
             \ /
              I
               \
                * (Tag: v1.6.9)

Now our new feature is finished. However, since our bugfix was merged at G,
there have been changes in master since we started. We could merge these into
our branches as well, but since those changes are not public yet, it makes more
sense to do a rebase.
This can be accomplished by running the following on our `new-topic` branch:

    git pull --rebase origin master

This will pick up our changes and re-apply them on the new tree. In this case,
Where previously our topic started at commit F, it will now start at commit J:

          E       G---H (new-topic)
         / \     /
    A---B---F---J (master)
             \ /
              I
               \
                * (Tag: v1.6.9)

Now our topic is ready to be reviewed and merged. Just like before, we'll end up
with a tree like:


          E       G---H
         / \     /     \
    A---B---F---J-------K (master)
             \ /
              I
               \
                * (Tag: v1.6.9)

Next the inevitable happens, and we need to do a bugfix on our release.
We'll re-open the branch on the tag with the following command:

    git checkout -b 1.6.x v1.6.x

We'll make our changes and merge them upwards again ending with a working tree:


          E       G---H
         / \     /     \
    A---B---F---J-------K---M (master)
             \ /           /
              I-----------L (1.6.x)
               \
                * (Tag: v1.6.9)

Finally, just as before, when the changes are published, we'll tag the results
and close our release branch again:


          E       G---H
         / \     /     \
    A---B---F---J-------K---M (master)
             \ /           /
              I-----------L
               \           \
                \           * (Tag: v1.6.10)
                 \
                  * (Tag: v1.6.9)

== Commit History

=== Commit Message

We will follow http://chris.beams.io/posts/git-commit/['The seven rules of a great Git commit message']
when creating commit messages. They are as follows.

. Separate subject from body with a blank line
. Limit the subject line to 50 characters
. Capitalize the subject line
. Do not end the subject line with a period
. Use the imperative mood in the subject line
. Wrap the body at 72 characters
. Use the body to explain what and why vs. how

=== Clean History

To keep a clean commit history, which makes reviewing pull requests, and
rewinding code a easier process, commits on branches SHOULD be complete,
that is buildable, as well as follow The Seven Rules described above. The RECOMMENDED
solution to achieve this is to use the `--amend` flag for committing when
making multiple edits to a branch or where many commits have already been made
during the development process use rebase command to re-write history.

= README

Every project MUST have a README file. The README MUST be a text file, this
file MAY use a markup language as long as it is easy to read without the use
of a text processor. For example; plain text (.txt),
https://guides.github.com/features/mastering-markdown/[markdown] (.md), or
http://asciidoctor.org/[asciidoctor] (.adoc) would all be fine choices.

The README should contain all information possible about the project. It should
be the source of truth that will allow a developer to easily find anything
they need to know about the project. This should include but is not limited to
links to JIRA, git, Buddy Build, documentation on how to set up the project,
and how to release the project.

The following README template SHOULD be used for projects.

[README.md]
```
# Project Name

## Important Project links

<!--
Place important project links here, anything and everything that is related to
this project should be documented here.
-->

- [Source](https://github.com/one20inc/cool-project)
- [JIRA](one20inc.atlassian.net/insane-jira-url-to-project)
- [Buddy Build](https://dashboard.buddybuild.com/apps/58d984594615aa0001d540fb)
- [Fabric](https://fabric.io/android/apps/cool.project/)
- [Firebase](https://console.firebase.google.com/project/cool-project/overview)
- [Play Store](https://play.google.com/store/apps/details?id=cool.project.android)
- [Notes and Wires](https://drive.google.com/drive/u/1/folders/0B5j3shyAKaAnRks4b1hNY2kxWUE)

## Build Types
<!--
Give each build variant/flavor a different section here. Explain what each
does, why one would use it, what features each has, links to associated
services (ie. crashlytics, firebase), which should be given to clients, and what
signing keys are used.
-->

## Project Setup
<!--
Describe step by step setup and any dependencies that are required and
their setup as well.
-->

## In Scope Devices
<!--
List out devices that are in scope here.
-->

## Contributing
<!--
Include any special requirements for contributing to the project. Are there
special style guides that must be followed? Is there a different flow for
doing pull requests. Anything else that might be relevant for contributing.
-->
```

NOTE: The above is a guideline for creating a good README, but anything that
is thought to be useful in a README should be included. Anything about a project
that differs from standard operating procedure SHOULD be documented in the
README.

= Testing

== Unit Testing

Unit Tests SHOULD be implemented for all code that does not have direct dependencies
on `android` packages and does some amount of work. That is any code
that is not in the views, fragments or activities, should be tested.
Not having the time to unit test is not a valid excuse for not testing. Time
is always saved in the long run when testing.

== UI Tests / Functional / Instrumentation Tests

All of these types of testing are RECOMMENDED, but should be considered on a
case by case basis to see if they fit for the project.

= Continuous Integration

All Android Projects at The One20 MUST use CI.
https://dashboard.buddybuild.com[Buddybuild] is a quick and
convenient way to set this up with our Github organization.

Buddybuild setup requires access to our Github organization, but after that setting it up 
can be done https://dashboard.buddybuild.com/apps/wizard/build/select-repo[here]

= Logging

Logging is very important in be able to quickly debug applications. For this
the reason The One20 Android Developers have adopted
https://github.com/InkApplications/android-logger[android-logger] as the logger of choice.
This combined with our Dagger setup makes it easy to log to all sources at once, 
and easily disable logging to logcat from release variants.

Release builds MUST NOT log to logcat. This is a security concern as well as a
performance issue. Logs SHOULD instead be sent to Crashlytics, Google Analytics,
Firebase, Loggy, or some other comparable cloud logging option where they can
be reviewed and used to debug issues.
